spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8081/configServer
  profiles:
    active: dev
          
eureka:
  instance:
    hostname: localhost
    