spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Debjyoti2/microserviceWithKafkaCentralConfig.git
          clone-on-start: true
          default-label: main
    
server:
  port: 8081
  servlet:
    context-path: /configServer
eureka:
  instance:
    hostname: localhost
   